live_config_reload = true

import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new-session -d -s home"]

[cursor]
style.blinking = "Always"

[font]
size = 20

[font.normal]
family = "agave Nerd Font Mono"
style = "r"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.00

[window.padding]
x = 18
y = 18

[env]
TERM = "xterm-256color"
