live_config_reload = true

[font]
size = 20

[font.normal]
family = "agave Nerd Font Mono"
style = "r"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
